### ISSUE TITLE
Page_info这个类呢？

### ISSUE THREAD

**Issue by colinwong92** [reseelies/maofly_spider#1]
大佬求分享

**Comment by colinwong92** [comment]
输入章号后提示错误：DeprecationWarning: use options instead of chrome_options
  self.driver = webdriver.Chrome(chrome_options=chrome_options)
Exception in thread Thread-1 (exchange):
Traceback (most recent call last):
  File "C:\Users\colin\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 71, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\colin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\colin\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

**Comment by reseelies** [comment]
不好意思，这个问题我也是第一次遇到，但根据描述，我认为您可以做出以下更改以解决问题：
self.driver = webdriver.Chrome(chrome_options=chrome_options) 
更改为：
self.driver = webdriver.Chrome(options=chrome_options) 


该问题可能是 selenium 版本升级导致的，如果无法解决问题，请反馈，我还会做出进一步的更改。
还有，我不是大佬，我只是个在校大学生，专业也不是计算机，感谢您使用我写的程序，我写的程序有很多不足之处，谢谢您对我代码中问题的反馈。

**Comment by colinwong92** [comment]
您好，改了后还是有问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月20日(星期三) 晚上11:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [reseelies/maofly_spider] Page_info这个类呢？ (Issue #1)





 
不好意思，这个问题我也是第一次遇到，但根据描述，我认为您可以做出以下更改以解决问题：
 self.driver = webdriver.Chrome(chrome_options=chrome_options)
 更改为：
 self.driver = webdriver.Chrome(options=chrome_options)
 
该问题可能是 selenium 版本升级导致的，如果无法解决问题，请反馈，我还会做出进一步的更改。
 还有，我不是大佬，我只是个在校大学生，专业也不是计算机，感谢您使用我写的程序，我写的程序有很多不足之处，谢谢您对我代码中问题的反馈。

**Comment by reseelies** [comment]
您好，不好意思，我之前搞错了，这是多线程的问题，不是selenium的问题。
多线程的问题很复杂，具体错误原因我也不清楚，我更新了我的代码，并添加了单线程的版本，该版本更稳定，但会更慢，多线程版本也做了更新，可能有所改善。

**Comment by colinwong92** [comment]
好的，谢谢您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月21日(星期四) 中午12:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [reseelies/maofly_spider] Page_info这个类呢？ (Issue #1)





 
您好，不好意思，我之前搞错了，这是多线程的问题，不是selenium的问题。
 多线程的问题很复杂，具体错误原因我也不清楚，我更新了我的代码，并添加了单线程的版本，该版本更稳定，但会更慢，多线程版本也做了更新，可能有所改善。
 
&mdash;

**Comment by colinwong92** [comment]
好像还是不行。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年7月21日(星期四) 中午12:23
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [reseelies/maofly_spider] Page_info这个类呢？ (Issue #1)





 
您好，不好意思，我之前搞错了，这是多线程的问题，不是selenium的问题。
 多线程的问题很复杂，具体错误原因我也不清楚，我更新了我的代码，并添加了单线程的版本，该版本更稳定，但会更慢，多线程版本也做了更新，可能有所改善。
 
&mdash;

**Comment by reseelies** [comment]
你加我QQ吧，在这里交流不太方便，QQ：2127409103
